PSIRSCashBook/Controllers/ItemsController.cs
using PSIRSCashBook.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PSIRSCashBook.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Items
        public async Task<ActionResult> Index()
        {
            var items = _db.Items.Include(i => i.PsirsCode);
            return View(await items.ToListAsync());
        }
        public async Task<ActionResult> GetIndex()
        {
            // dc.Configuration.LazyLoadingEnabled = false; // if your table is relational, contain foreign key
            var data = await _db.Items.Include(i => i.PsirsCode).AsNoTracking().Select(s => new
            {
                s.PsirsCode.CodeName,
                s.ItemName,
                s.ItemId
            }).ToListAsync();
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        public async Task<PartialViewResult> Save(int id)
        {
            var item = await _db.Items.FindAsync(id);
            ViewBag.PsirsCodeId = new SelectList(_db.PsirsCodes, "PsirsCodeId", "CodeName");
            return PartialView(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(Item model)
        {
            bool status = false;
            string message = string.Empty;
            if (ModelState.IsValid)
            {
                if (model.ItemId > 0)
                {
                    var item = await _db.Items.FindAsync(model.ItemId);
                    if (item != null)
                    {
                        item.ItemName = model.ItemName;
                        item.PsirsCodeId = model.PsirsCodeId;
                        _db.Entry(item).State = EntityState.Modified;
                        await _db.SaveChangesAsync();
                        message = $"{model.ItemName} Updated Successfully...";
                        return new JsonResult { Data = new { status = true, message = message } };
                    }
                }
                else
                {
                    _db.Items.Add(model);
                    await _db.SaveChangesAsync();
                    message = $"{model.ItemName} Added Successfully.";
                    return new JsonResult { Data = new { status = true, message = message } };
                }
            }
            return new JsonResult { Data = new { status = status, message = message } };
            //return View(subject);
        }

        // GET: Items/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await _db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.PsirsCodeId = new SelectList(_db.PsirsCodes, "PsirsCodeId", "CodeName");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Item item)
        {
            if (ModelState.IsValid)
            {
                _db.Items.Add(item);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PsirsCodeId = new SelectList(_db.PsirsCodes, "PsirsCodeId", "CodeName", item.PsirsCodeId);
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await _db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.PsirsCodeId = new SelectList(_db.PsirsCodes, "PsirsCodeId", "CodeName", item.PsirsCodeId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Item item)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(item).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PsirsCodeId = new SelectList(_db.PsirsCodes, "PsirsCodeId", "CodeName", item.PsirsCodeId);
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await _db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Item item = await _db.Items.FindAsync(id);
            _db.Items.Remove(item);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PSIRSCashBook/Controllers/StaffsController.cs
using PSIRSCashBook.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PSIRSCashBook.Controllers
{
    public class StaffsController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Staffs
        public ActionResult Index()
        {
            return View();
        }


        public async Task<ActionResult> GetIndex(string gender)
        {
            #region Server Side filtering

            //Get parameter for sorting from grid table
            // get Start (paging start index) and length (page size for paging)
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            //Get Sort columns values when we click on Header Name of column
            //getting column name
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            //Soring direction(either desending or ascending)
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            string search = Request.Form.GetValues("search[value]").FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int totalRecords = 0;

            var studentIndex = new List<Staff>();

            if (!string.IsNullOrEmpty(search))
            {
                var v = await _db.Staffs.AsNoTracking()
                                        .Where(x => x.StaffId.ToUpper().Equals(search.ToUpper().Trim())
                                        || x.FirstName.ToUpper().Equals(search.ToUpper().Trim())
                                        || x.LastName.ToUpper().Equals(search.ToUpper().Trim())
                                        || x.MiddleName.ToUpper().Equals(search.ToUpper().Trim()))
                                        .ToListAsync();
                // Mapping the student to the correct ViewModel for json display
                studentIndex.AddRange(v);
            }
            else
            {
                var v = await _db.Staffs.AsNoTracking().ToListAsync();
                // Mapping the student to the correct ViewModel for json display
                studentIndex.AddRange(v);
            }

            totalRecords = studentIndex.Count();
            var data = studentIndex.Skip(skip).Take(pageSize).ToList();

            return Json(new { draw = draw, recordsFiltered = totalRecords, recordsTotal = totalRecords, data = data },
                JsonRequestBehavior.AllowGet);

            #endregion Server Side filtering
        }


        public async Task<PartialViewResult> PartialDetails(string id)
        {
            if (id == null)
            {
                id = "";
            }

            var staff = await _db.Staffs.FindAsync(id);

            return PartialView(staff);
        }

        // GET: Staffs/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await _db.Staffs.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "StaffId,Designation,MaritalStatus,IsActiveStaff,ActiveStatus,FirstName,MiddleName,LastName,Gender,Email,PhoneNumber,Religion,TownOfBirth,StateOfOrigin,Nationality,CountryOfBirth,DateOfBirth,Age,Passport")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _db.Staffs.Add(staff);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await _db.Staffs.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            var mystates = from State s in Enum.GetValues(typeof(State))
                           select new { ID = s, Name = s.ToString() };
            var religion = from Religion s in Enum.GetValues(typeof(Religion))
                           select new { ID = s, Name = s.ToString() };
            var mygender = from Gender s in Enum.GetValues(typeof(Gender))
                           select new { ID = s, Name = s.ToString() };
            var maritalStatus = from Maritalstatus s in Enum.GetValues(typeof(Maritalstatus))
                                select new { ID = s, Name = s.ToString() };

            ViewBag.MaritalStatus = new SelectList(maritalStatus, "Name", "Name");
            ViewBag.Religion = new SelectList(religion, "Name", "Name");
            ViewBag.StateOfOrigin = new SelectList(mystates, "Name", "Name");
            ViewBag.Gender = new SelectList(mygender, "Name", "Name");
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Staff staff)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(staff).State = EntityState.Modified;
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            var mystates = from State s in Enum.GetValues(typeof(State))
                           select new { ID = s, Name = s.ToString() };
            var religion = from Religion s in Enum.GetValues(typeof(Religion))
                           select new { ID = s, Name = s.ToString() };
            var mygender = from Gender s in Enum.GetValues(typeof(Gender))
                           select new { ID = s, Name = s.ToString() };
            var maritalStatus = from Maritalstatus s in Enum.GetValues(typeof(Maritalstatus))
                                select new { ID = s, Name = s.ToString() };

            ViewBag.MaritalStatus = new SelectList(maritalStatus, "Name", "Name");
            ViewBag.Religion = new SelectList(religion, "Name", "Name");
            ViewBag.StateOfOrigin = new SelectList(mystates, "Name", "Name");
            ViewBag.Gender = new SelectList(mygender, "Name", "Name");
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = await _db.Staffs.FindAsync(id);
            if (staff == null)
            {
                return HttpNotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Staff staff = await _db.Staffs.FindAsync(id);
            _db.Staffs.Remove(staff);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PSIRSCashBook/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>PSIRS | Dashboard</title>

    <link href="~/Content/AdminTemplate/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/AdminTemplate/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/Content/AdminTemplate/css/plugins/dataTables/datatables.min.css" rel="stylesheet">
    <!-- Toastr style -->
    <link href="~/Content/AdminTemplate/css/plugins/toastr/toastr.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="~/Content/AdminTemplate/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">


    <link href="~/Content/AdminTemplate/css/animate.css" rel="stylesheet">
    <link href="~/Content/AdminTemplate/css/style.css" rel="stylesheet">

   

</head>

<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span>
                                @if (User.IsInRole("Admin") || User.IsInRole("Operator"))
                                {
                                    @*<img alt="image" class="img-circle img-responsive img-backdrop" src="@Url.Action("RenderImage", "Staffs", new { staffId = User.Identity.GetUserId()})" />*@
                                    <img alt="image" class="img-circle img-responsive img-backdrop" src="" />
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                        <span class="clear">
                                            <span class="block m-t-xs">
                                                <strong class="font-bold">@ViewBag.FullName</strong>
                                            </span> <span class="text-muted text-xs block">Staff <b class="caret"></b></span>
                                        </span>
                                    </a>
                                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                        <li><a href="profile.html">Profile</a></li>
                                        <li><a href="contacts.html">Contacts</a></li>
                                        <li><a href="mailbox.html">Mailbox</a></li>
                                        <li class="divider"></li>
                                        <li><a href="@Url.Action("LogOff","Account")">Logout</a></li>
                                    </ul>
                                }

                                else
                                {
                                    <img alt="image" class="img-circle" src="" />
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                        <span class="clear">
                                            <span class="block m-t-xs">
                                                <strong class="font-bold">@ViewBag.FullName</strong>
                                            </span> <span class="text-muted text-xs block"> <b class="caret"></b></span>
                                        </span>
                                    </a>
                                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                        <li><a href="profile.html">Profile</a></li>
                                        <li><a href="contacts.html">Contacts</a></li>
                                        <li><a href="mailbox.html">Mailbox</a></li>
                                        <li class="divider"></li>
                                        <li><a href="@Url.Action("LogOff","Account")">Logout</a></li>
                                    </ul>
                                }
                            </span>


                        </div>
                        <div class="logo-element">
                            PSIRS
                        </div>
                    </li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="active">
                            <a href="@Url.Action("AdminDashBoard", "Home")"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span> </a>
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-user-md"></i> <span class="nav-label">Staff Management</span><span class="fa arrow"></span> </a>
                            <ul class="nav nav-second-level collapse">
                                <li>@Html.ActionLink("Add Staff", "RegisterStaff", "Account")</li>
                                <li>@Html.ActionLink("View Staff", "Index", "Staffs")</li>
                                <li>@Html.ActionLink("Assign Role", "Index", "Staffs")</li>

                            </ul>
                        </li>
                        <li class="active">
                            <a href="@Url.Action("Index", "PsirsCodes")"><i class="fa fa-th-large"></i> <span class="nav-label">Psirs Code</span> </a>
                        </li>
                        <li class="active">
                            <a href="@Url.Action("Index", "Items")"><i class="fa fa-th-large"></i> <span class="nav-label">Code Item</span> </a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-money"></i> <span class="nav-label">CashBook</span><span class="fa arrow"></span> </a>
                            <ul class="nav nav-second-level collapse">
                                <li>@Html.ActionLink("Add CashBook", "Create", "CashBooks")</li>
                                <li>@Html.ActionLink("View CashBook", "Index", "CashBooks")</li>
                            </ul>
                        </li>


                    }
                    else if (Request.IsAuthenticated && User.IsInRole("Operator"))
                    {
                        <!-- BEGIN DASHBOARD -->
                        <li class="active">
                            <a href="@Url.Action("OperatorDashBoard", "Home")"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span> </a>
                        </li>
                        <!-- END DASHBOARD -->
                        <!-- BEGIN SCHOOL SETUP -->
                        <li>
                            <a href="#"><i class="fa fa-cogs "></i> <span class="nav-label">School Settings</span> <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse">
                                <li>@Html.ActionLink("Faculty", "Index", "Faculties")</li>
                                <li>@Html.ActionLink("Departments", "Index", "Departments")</li>
                                <li>@Html.ActionLink("Dept Option", "Index", "Programmes")</li>
                                <li>@Html.ActionLink("Sessions", "Index", "Sessions")</li>
                                <li>@Html.ActionLink("Semesters", "Index", "Semesters")</li>
                                <li>@Html.ActionLink("List Level", "Index", "Levels")</li>
                                <li>@Html.ActionLink("Final Level", "Index", "FacultyFinalLevels")</li>
                            </ul>
                        </li>
                        <!-- END SCHOOL SETUP -->

                        <!-- END Role/profile -->
                    }


                    <div class="menubar-foot-panel">
                        <small class="no-linebreak hidden-folded">
                            <span class="opacity-75">
                                @*<img class="img-responsive" src="~/Content/Images/compunetLogo.png" width="200" hiegth="50" />*@
                            </span>
                        </small>
                    </div>

                </ul>
            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" action="http://webapplayers.com/inspinia_admin-v2.7.1/search_results.html">
                            <div class="form-group">
                                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">Welcome to PSIRS Cashbook</span>
                        </li>

                        <li>
                            <a href="@Url.Action("LogOff","Account")">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                        <li>
                            <a class="right-sidebar-toggle">
                                <i class="fa fa-tasks"></i>
                            </a>
                        </li>
                    </ul>

                </nav>
            </div>
            @RenderBody()


        </div>



    </div>


    <script src="~/Content/AdminTemplate/js/jquery-3.1.1.min.js"></script>
    <script src="~/Content/AdminTemplate/js/bootstrap.min.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/dataTables/datatables.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/Content/AdminTemplate/js/inspinia.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/pace/pace.min.js"></script>

    <!-- jQuery UI -->
    <script src="~/Content/AdminTemplate/js/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Toastr -->
    <script src="~/Content/AdminTemplate/js/plugins/toastr/toastr.min.js"></script>




    <script>
        $(document).ready(function () {
            setTimeout(function () {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                //toastr.success('Responsive Admin Theme', 'Welcome to INSPINIA');

            }, 1300);

        });
    </script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '../../www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-4625583-2', 'webapplayers.com');
        ga('send', 'pageview');

    </script>
    @RenderSection("scripts", required: false)
</body>

</html>

PSIRSCashBook/Views/Shared/_LayoutLanding.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PSIRS - Landing Page</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/AdminTemplate/css/bootstrap.min.css" rel="stylesheet">

    <!-- Animation CSS -->
    <link href="~/Content/AdminTemplate/css/animate.css" rel="stylesheet">
    <link href="~/Content/AdminTemplate/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/AdminTemplate/css/style.css" rel="stylesheet">
</head>
<body id="page-top" class="landing-page no-skin-config">
    <div class="navbar-wrapper">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="@Url.Action("Index","Home")">PSIRS</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a class="page-scroll" href="#page-top">Home</a></li>
                        <li><a class="page-scroll" href="@Url.Action("Login", "Account")">Login</a></li>
                        <li><a class="page-scroll" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
@RenderBody()

    <!-- Mainly scripts -->
    <script src="~/Content/AdminTemplate/js/jquery-3.1.1.min.js"></script>
    <script src="~/Content/AdminTemplate/js/bootstrap.min.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/Content/AdminTemplate/js/inspinia.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/pace/pace.min.js"></script>
    <script src="~/Content/AdminTemplate/js/plugins/wow/wow.min.js"></script>


    <script>

    $(document).ready(function () {

        $('body').scrollspy({
            target: '.navbar-fixed-top',
            offset: 80
        });

        // Page scrolling feature
        $('a.page-scroll').bind('click', function(event) {
            var link = $(this);
            $('html, body').stop().animate({
                scrollTop: $(link.attr('href')).offset().top - 50
            }, 500);
            event.preventDefault();
            $("#navbar").collapse('hide');
        });
    });

    var cbpAnimatedHeader = (function() {
        var docElem = document.documentElement,
                header = document.querySelector( '.navbar-default' ),
                didScroll = false,
                changeHeaderOn = 200;
        function init() {
            window.addEventListener( 'scroll', function( event ) {
                if( !didScroll ) {
                    didScroll = true;
                    setTimeout( scrollPage, 250 );
                }
            }, false );
        }
        function scrollPage() {
            var sy = scrollY();
            if ( sy >= changeHeaderOn ) {
                $(header).addClass('navbar-scroll')
            }
            else {
                $(header).removeClass('navbar-scroll')
            }
            didScroll = false;
        }
        function scrollY() {
            return window.pageYOffset || docElem.scrollTop;
        }
        init();

    })();

    // Activate WOW.js plugin for animation on scrol
    new WOW().init();

    </script>

</body>
</html>